workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - build
  - test
  - lint
  - build-image
  - deploy

build:maven:
  stage: build
  image: maven:3.9.8-sapmachine-21
  script:
    - echo "Building artifact with Maven..."
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar

test:maven:
  stage: test
  image: maven:3.9.8-sapmachine-21
  script:
    - echo "Running tests with Maven..."
    - mvn test
  needs:
    - build:maven

lint:check:
  stage: lint
  image: maven:3.9.8-sapmachine-21
  script:
    - echo "Running code quality checks..."
    - mvn checkstyle:check
  needs:
    - build:maven

build:docker:
  stage: build-image
  image: docker:20.10
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "Building Docker image..."
    - export TAG=$(echo $CI_COMMIT_REF_NAME | tr '/' '-')
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:$TAG .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:$TAG
  needs:
    - build:maven
    - test:maven
    - lint:check
  dependencies:
    - build:maven

deploy:
  stage: deploy
  script:
    - echo "Deploying artifact...WIP"