flyway.url=jdbc:postgresql://${APPLICATION_DATABASE_HOSTNAME}/${APPLICATION_DATABASE_NAME}
flyway.user=${APPLICATION_DATABASE_USERNAME}
flyway.password=${APPLICATION_DATABASE_PASSWORD}
flyway.locations=src/main/resources/db/migration
flyway.cleanDisabled=false