flyway.url=jdbc:postgresql://localhost:5432/leacooking
flyway.user=postgres
flyway.password=postgres
flyway.locations=src/main/resources/db/migration,src/main/resources/db/env/dev
flyway.cleanDisabled=false
#flyway.outOfOrder=true