spring.application.name=LeaCooking
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#################################
# --- APPLICATION VARIABLES --- #
#################################

spring.datasource.url=jdbc:postgresql://localhost:5432/leacooking
spring.datasource.username=postgres
spring.datasource.password=postgres